"""Compare two checkpoints from random positions instead of the opening.

    python -m scripts.randomPositionSweep models/Talos1.0 models/Talos1.1
    python -m scripts.randomPositionSweep --positions 50 models/a models/b

``scripts/openingSweep.py`` measures the two checkpoints where every recorded
number so far was measured: at the start of a game, or two plies into one. That
is the position a policy has seen most and is least likely to misplay. This
script asks the other question -- whether a checkpoint still plays well from
positions it has no reason to be familiar with -- by dealing each game a
starting position built from uniformly random legal moves.

Uniformly random, deliberately, and not sampled from either policy: a position
distribution generated by one of the two contestants would favour whichever one
produced it, which is the one thing a benchmark must not do. The cost is that
some of these positions are ones no sensible game reaches. That is the point --
they are the breadth being measured -- but it does mean a score here answers
"how well does it cope off its own track", not "how strong is it", and the
opening sweep remains the answer to the second.

**Each position is played twice, with the two checkpoints swapping seats.** A
random position is not fair -- it may hand one seat a won game before either
policy moves -- and neither is the side to move. Playing the mirror cancels
both exactly, so a pair of games measures the players rather than the deal.
Unlike the opening sweep, which enumerates *all* 800 two-ply openings and is
therefore a census, this is a sample of a much larger space, so the score does
carry a confidence interval. The unit for it is the *pair*, not the game: the
two games of a pair share a position and are not independent, and treating them
as two samples would understate the interval by up to a factor of root two.
"""

from __future__ import annotations

import argparse
import math

import numpy as np

from env.halmaEnv import HalmaEnv
from env.neuralPlayer import NeuralComputer
from game.boardTypes import MovePath
from scripts.openingSweep import buildGame


def randomPosition(
    seatOne: NeuralComputer,
    seatTwo: NeuralComputer,
    firstSeat: int,
    rng: np.random.Generator,
    plies: int,
) -> list[MovePath]:
    """The moves that deal one starting position, as a replayable list.

    Returned as moves rather than as a board, because the same position has to
    be set up twice -- once per seat assignment -- and replaying a move list
    into a fresh game is the only way to build a position this engine will
    accept as its own. The players passed in are never consulted; a game object
    is needed to walk the moves, and it needs two seats filled.
    """
    game, _ = buildGame(seatOne, seatTwo, firstSeat)
    moves: list[MovePath] = []
    for _ in range(plies):
        # Unreachable at any sane ply count -- the shortest game here is far
        # longer -- but a deal must not be able to walk past the end of a game.
        if game.winner() is not None:
            break
        player = game.currentPlayer()
        legal = game.board.allValidMovesWithWay(player)
        move = legal[int(rng.integers(len(legal)))]
        game.playMove(player, move)
        moves.append(move)
    return moves


def playFrom(
    seatOne: NeuralComputer,
    seatTwo: NeuralComputer,
    firstSeat: int,
    moves: list[MovePath],
) -> tuple[int | None, int]:
    """Replay a dealt position, then play it out argmax to the end."""
    game, _ = buildGame(seatOne, seatTwo, firstSeat)
    for move in moves:
        game.playMove(game.currentPlayer(), move)
    while game.winner() is None and game.gameLength() < game.MAX_MOVES:
        game.playNextMove(game.currentPlayer())
    return game.winner(), game.gameLength()


def scoreLine(label: str, scores: list[float]) -> str:
    """Mean score with a 95% interval, or without one if a single pair."""
    mean = float(np.mean(scores)) * 100
    if len(scores) < 2:
        return f"    {label:<34} {mean:5.1f} %"
    error = 1.96 * float(np.std(scores, ddof=1)) / math.sqrt(len(scores)) * 100
    return f"    {label:<34} {mean:5.1f} % +/- {error:4.1f}   ({len(scores)} pairs)"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("checkpoints", nargs=2, help="the two model paths to compare")
    parser.add_argument(
        "--positions", type=int, default=200, help="positions to deal (each played twice)"
    )
    # The range covers the opening being left behind through the middlegame.
    # Drawn per position rather than fixed, so the result is not a statement
    # about one particular depth.
    parser.add_argument("--minPlies", type=int, default=4, help="shallowest deal")
    parser.add_argument("--maxPlies", type=int, default=20, help="deepest deal")
    parser.add_argument(
        "--seed",
        type=int,
        default=0,
        help="fixes the deal, so every checkpoint is scored on the same positions",
    )
    args = parser.parse_args()
    if args.minPlies < 0 or args.maxPlies < args.minPlies:
        parser.error("--minPlies must be >= 0 and no greater than --maxPlies")

    pathOne, pathTwo = args.checkpoints
    # Four seatings, because the mirror needs each checkpoint on each seat, and
    # a NeuralComputer's encoder is keyed to the seat it was built for.
    oneOnSeatOne = NeuralComputer(HalmaEnv.AGENT_SEAT, pathOne, deterministic=True)
    oneOnSeatTwo = NeuralComputer(HalmaEnv.OPPONENT_SEAT, pathOne, deterministic=True)
    twoOnSeatOne = NeuralComputer(HalmaEnv.AGENT_SEAT, pathTwo, deterministic=True)
    twoOnSeatTwo = NeuralComputer(HalmaEnv.OPPONENT_SEAT, pathTwo, deterministic=True)

    # Its own generator, seeded from the command line and untouched by the
    # games, so the same --seed deals the same positions to any pair of
    # checkpoints -- that is what makes two runs of this script comparable.
    rng = np.random.default_rng(args.seed)
    midpoint = (args.minPlies + args.maxPlies) // 2

    scores: list[float] = []
    shallow: list[float] = []
    deep: list[float] = []
    swept = {"wonBoth": 0, "lostBoth": 0, "split": 0, "draws": 0}
    lengths: list[int] = []

    for index in range(args.positions):
        # Alternated rather than drawn: the side to move at the deal is part
        # of the position, and half of each is what an even split guarantees.
        firstSeat = HalmaEnv.AGENT_SEAT if index % 2 == 0 else HalmaEnv.OPPONENT_SEAT
        plies = int(rng.integers(args.minPlies, args.maxPlies + 1))
        moves = randomPosition(oneOnSeatOne, twoOnSeatTwo, firstSeat, rng, plies)

        # The mirror: same position, same side to move, seats swapped.
        firstWinner, firstLength = playFrom(oneOnSeatOne, twoOnSeatTwo, firstSeat, moves)
        secondWinner, secondLength = playFrom(twoOnSeatOne, oneOnSeatTwo, firstSeat, moves)
        lengths += [firstLength, secondLength]

        # Half a point per game for pathOne, so a pair scores 0, 0.5 or 1 --
        # a draw splits the game it happened in rather than voiding the pair.
        points = 0.0
        for winner, seatOfPathOne in (
            (firstWinner, HalmaEnv.AGENT_SEAT),
            (secondWinner, HalmaEnv.OPPONENT_SEAT),
        ):
            if winner is None:
                points += 0.25
                swept["draws"] += 1
            elif winner == seatOfPathOne:
                points += 0.5
        scores.append(points)
        (shallow if plies <= midpoint else deep).append(points)
        if points == 1.0:
            swept["wonBoth"] += 1
        elif points == 0.0:
            swept["lostBoth"] += 1
        else:
            swept["split"] += 1

        if (index + 1) % 25 == 0:
            running = float(np.mean(scores)) * 100
            print(f"  {index + 1:>4} positions   {pathOne} {running:5.1f} %", flush=True)

    print(
        f"\n=== {2 * len(scores)} games from {len(scores)} mirrored positions, "
        f"{args.minPlies}-{args.maxPlies} random plies, seed {args.seed}"
    )
    print(scoreLine(pathOne, scores))
    print(scoreLine(pathTwo, [1.0 - score for score in scores]))
    print(f"    {'average length':<34} {float(np.mean(lengths)):5.0f} moves")
    print(f"\n    {'pairs won by ' + pathOne:<34} {swept['wonBoth']:>5}")
    print(f"    {'pairs won by ' + pathTwo:<34} {swept['lostBoth']:>5}")
    # Mostly pairs the position decided rather than the players: each
    # checkpoint won whichever side the deal put ahead. A high count means the
    # deals are lopsided, which caps how far this score can separate two
    # checkpoints at all.
    print(f"    {'pairs neither won both':<34} {swept['split']:>5}")
    print(f"    {'drawn games':<34} {swept['draws']:>5}")
    # Whether the gap survives going further off the beaten track, which is
    # the thing this script exists to see and a single total would hide.
    print(f"\n{pathOne} by how far the deal ran:")
    if shallow:
        print(scoreLine(f"{args.minPlies}-{midpoint} plies", shallow))
    if deep:
        print(scoreLine(f"{midpoint + 1}-{args.maxPlies} plies", deep))


if __name__ == "__main__":
    main()
